export type Condition = { sex?: number; age_band?: string; residence?: string; wealth_quintile?: number; bmi_band?: string; hypertension?: number; tobacco?: number; alcohol?: number; state?: number | null }
export type RunStatus = { run_type?: 'mock'|'quick'|'full'|null; preliminary?: boolean; status_banner?: string; run_note?: string|null; demo?: boolean }
export type HealthResponse = RunStatus & { status: string; mode: string; model_fingerprint?: string|null; detail?: string|null; version: string; model: string; disclaimer_present: boolean }
export type SchemaResponse = Record<string, unknown> & { supported_state_codes?: number[] }
export type OptionsResponse = { state: number[]; sex: number[]; age_band: { women_options: string[]; men_options: string[] }; residence: string[]; wealth_quintile: number[]; bmi_band: string[]; hypertension: number[]; tobacco: number[]; alcohol: number[]; required_profile_keys: string[] }
export type Profile = { label: string; condition: Condition; description: string; n_train: number }
export type ProfilesResponse = RunStatus & { profiles: Profile[]; source: string; reference_scope: string; disclaimer: string }
export type GenerateRequest = { condition: Condition; n?: number; n_examples?: number; seed?: number }
export type Outcome = { rate: number; ci_low: number; ci_high: number; n: number; rate_pct: number; dropped_nonfinite?: number|null; monte_carlo_interval?: Record<string, unknown>|null }
export type SyntheticExample = { example_id: string; synthetic: true; label: string; effective_conditions: Condition; generated_features: Record<string, number|string|null>; glucose_raw: number; elevated_glucose_proxy: boolean; illustrative_elevated: boolean }
export type GenerateResponse = RunStatus & { examples: SyntheticExample[]|null; examples_status: string; examples_note: string; condition: Condition; effective_conditions: Condition; outcome_stat: Outcome; model_fingerprint: string; sampling_diagnostics: Record<string, number|string|boolean|null>; synthetic: true; banner?: string|null; model_used: string; scope: string; weighting: string; uncertainty_note: string; disclaimer: string; note: string }
export type CompareScenarioRequest = GenerateRequest & { label: string }
export type CompareRequest = { scenarios: CompareScenarioRequest[] }
export type ScenarioResult = GenerateResponse & { label: string; delta_pp: number }
export type CompareResponse = RunStatus & { scenarios: ScenarioResult[]; model_fingerprint: string; disclaimer: string; weighting: string; uncertainty_note: string; note: string }
export type ValidationResponse = RunStatus & { status: string; metrics?: Record<string, unknown>|null; models?: Record<string, unknown>|null; evaluation_scope?: Record<string, unknown>|null; real_reference?: Record<string, unknown>|null; model_fingerprint?: string|null; note: string }
export type ParseRequest = { text: string; baseline?: Condition|null }
export type ParseResponse = { parsed_condition: Condition; raw_text: string; confidence?: number|null; parser: string; requires_confirmation: boolean; unresolved: string[]; optional_token_hook?: Record<string, unknown>|null }
export type ApiError = { detail?: string|{msg?: string;loc?: (string|number)[]}[]; [key: string]: unknown }
