import { useEffect, useState } from 'react'
import { ArrowRight, Check, ChevronDown, Sparkles } from 'lucide-react'
import type { Condition, GenerateResponse, OptionsResponse, Profile } from '../../types/api'
import api from '../../services/api'
import { Loading } from '../ui/Blocks'
const required=['sex','age_band','residence','wealth_quintile','bmi_band','hypertension','tobacco','alcohol'] as const
const title:Record<string,string>={sex:'Sex',age_band:'Age band',residence:'Residence',wealth_quintile:'Wealth quintile',bmi_band:'BMI band',hypertension:'Hypertension',tobacco:'Tobacco use',alcohol:'Alcohol use',state:'State (optional)'}
const text=(key:string,value:unknown)=>{if(key==='sex')return Number(value)===0?'Female':'Male';if(key==='residence')return String(value).replace(/^./,x=>x.toUpperCase());if(key==='wealth_quintile')return `Quintile ${value}`;if(['hypertension','tobacco','alcohol'].includes(key))return Number(value)?'Yes':'No';if(key==='bmi_band')return String(value).replace(/^./,x=>x.toUpperCase());return String(value)}
export function ProfileForm({initial,onSubmit,submitLabel='Generate baseline',busy=false}:{initial?:Condition|null;onSubmit:(c:Condition)=>void;submitLabel?:string;busy?:boolean}){
 const [,setSchema]=useState<Record<string,unknown>|null>(null),[options,setOptions]=useState<OptionsResponse|null>(null),[profiles,setProfiles]=useState<Profile[]>([]),[error,setError]=useState(''),[profileNotice,setProfileNotice]=useState(''),[condition,setCondition]=useState<Condition>(initial??{})
 useEffect(()=>{let alive=true;Promise.allSettled([api.getSchema(),api.getOptions(),api.getProfiles()]).then(([s,o,p])=>{if(!alive)return;if(s.status==='fulfilled')setSchema(s.value);else setProfileNotice(`Schema detail unavailable: ${s.reason instanceof Error?s.reason.message:'request failed'}`);if(o.status==='fulfilled')setOptions(o.value);else setError(o.reason instanceof Error?o.reason.message:'Supported options could not be loaded.');if(p.status==='fulfilled')setProfiles(p.value.profiles);else setProfileNotice((old)=>[old,p.reason instanceof Error?`Presets unavailable; you can still build a profile manually. ${p.reason.message}`:'Presets unavailable; you can still build a profile manually.'].filter(Boolean).join(' '))});return()=>{alive=false}},[])
 useEffect(()=>{if(initial)setCondition(initial)},[initial])
 const set=(key:keyof Condition,value:string)=>setCondition(c=>{const next={...c,[key]:value===''?undefined:key==='sex'||key==='wealth_quintile'||key==='hypertension'||key==='tobacco'||key==='alcohol'||key==='state'?Number(value):value};if(key==='sex'&&options){const ageOptions=Number(value)===1?options.age_band.men_options:options.age_band.women_options;if(next.age_band&&!ageOptions.includes(next.age_band))next.age_band=undefined}return next})
 const valid=required.every(k=>condition[k]!==undefined&&condition[k]!==null)
 if(!options)return error?<div className="notice error">{error}<button className="text-button" onClick={()=>location.reload()}>Retry</button></div>:<Loading label="Loading supported profile options…"/>
 const fields:{key:keyof Condition; values:(string|number)[]}[]=[{key:'sex',values:options.sex},{key:'age_band',values:condition.sex===1?options.age_band.men_options:options.age_band.women_options},{key:'residence',values:options.residence},{key:'wealth_quintile',values:options.wealth_quintile},{key:'bmi_band',values:options.bmi_band},{key:'hypertension',values:options.hypertension},{key:'tobacco',values:options.tobacco},{key:'alcohol',values:options.alcohol},...(options.state.length?[{key:'state' as const,values:options.state}]:[])]
 return <div className="builder-card"><div className="preset-heading"><div><span className="eyebrow">START WITH A REFERENCE</span><h3>Choose a supported profile</h3></div><Sparkles size={18}/></div>{profileNotice&&<div className="notice">{profileNotice}</div>}{profiles.length>0?<div className="preset-row">{profiles.map((p,i)=><button type="button" key={`${p.label}-${i}`} className="preset" onClick={()=>{setCondition(p.condition);setError('')}}><span>{p.label}</span><small>{p.description}</small><ArrowRight size={14}/></button>)}</div>:<p className="muted">No supported presets were returned. Build a complete profile below.</p>}<div className="form-divider"><span/>or customize your profile<span/></div><div className="field-grid">{fields.map(({key,values})=><label className="field" key={key}><span>{title[key]}{required.includes(key as typeof required[number])&&<em>Required</em>}</span><div className="select-wrap"><select aria-label={title[key]} value={condition[key]===undefined||condition[key]===null?'':String(condition[key])} onChange={e=>set(key,e.target.value)}><option value="">Select {title[key].toLowerCase()}</option>{values.map(v=><option value={v} key={v}>{text(key,v)}</option>)}</select><ChevronDown size={15}/></div></label>)}</div><div className="form-bottom"><span className={valid?'valid-note':'hint-note'}>{valid?<><Check size={15}/>All required conditions selected</>:'Complete all eight required conditions to generate a cohort.'}</span><button className="button primary" disabled={!valid||busy} onClick={()=>onSubmit(condition)}>{busy?<><span className="spinner"/>Generating cohort</>:<>{submitLabel}<ArrowRight size={16}/></>}</button></div><p className="micro-note">Reference profiles are supported combinations, not real respondents. Glucose is an outcome and cannot be selected as a condition.</p></div>
}
export function conditionSummary(c?:Condition|null){if(!c)return 'No profile selected';return [`${c.sex===0?'Female':'Male'} · ${c.age_band}`,text('residence',c.residence),text('bmi_band',c.bmi_band),text('wealth_quintile',c.wealth_quintile),`Hypertension ${text('hypertension',c.hypertension)}`].filter(Boolean).join(' · ')}
export function MetricCard({result,title:heading='Generated Cohort Outcome Statistic'}:{result:GenerateResponse;title?:string}){const o=result.outcome_stat,scenarioId=result.examples?.[0]?.example_id.split('-')[0];return <section className="metric-card"><div className="metric-top"><span>{heading}</span><span className="synthetic-pill"><Sparkles size={13}/>SYNTHETIC COHORT</span></div><div className="metric-value">{o.rate_pct.toFixed(1)}<small>%</small></div><div className="metric-label">Elevated glucose (proxy)</div><div className="metric-divider"/><div className="metric-bottom"><div><small>95% interval</small><b>{(o.ci_low*100).toFixed(1)}% – {(o.ci_high*100).toFixed(1)}%</b></div><div><small>Synthetic cohort</small><b>{o.n.toLocaleString()} profiles</b></div><div><small>Scenario identifier</small><b>{scenarioId??'Not provided'}</b></div></div></section>}
export function Examples({result}:{result:GenerateResponse}){if(!result.examples?.length)return <div className="notice">Examples are unavailable for this scenario: {result.examples_status}. The cohort summary remains available.</div>;return <div className="example-grid">{result.examples.slice(0,5).map(ex=>{const f=ex.generated_features;return <article className="example-card" key={ex.example_id}><div className="example-head"><span>{ex.example_id}</span><span className="mock-label">SYNTHETIC · NOT A REAL PERSON</span></div><p className="example-warning">{ex.label}</p>{ex.illustrative_elevated&&<p className="illustration-note">Included to illustrate an elevated-glucose outcome.</p>}<div className="feature-grid">{[['Age',f.age,'years'],['BMI',f.bmi,'kg/m²'],['Waist',f.waist_cm,'cm'],['Hip',f.hip_cm,'cm'],['Weight',f.weight_kg,'kg'],['Height',f.height_cm,'cm'],['Education',f.education,''],['BP checked',f.bp_ever_checked===undefined?undefined:Number(f.bp_ever_checked)?'Yes':'No','']].filter(([,v])=>v!==undefined&&v!==null).map(([k,v,u])=><div key={String(k)}><small>{k}</small><b>{typeof v==='number'?Number(v).toFixed(k==='Age'||k==='Education'?0:1):v}{u&&<small> {u}</small>}</b></div>)}</div><div className="glucose-row"><span>Generated glucose</span><b>{ex.glucose_raw} mg/dL</b><span className={ex.elevated_glucose_proxy?'elevated':'not-elevated'}>{ex.elevated_glucose_proxy?'Elevated proxy':'Not elevated'}</span></div></article>})}</div>}
