import { useState } from 'react'
import { ArrowRight, GitCompareArrows } from 'lucide-react'
import { Link } from 'react-router-dom'
import api from '../services/api'
import { useAppState } from '../context/AppState'
import { conditionSummary, Examples, MetricCard, ProfileForm } from '../components/scenarios/ScenarioUI'
import { Disclaimer, ErrorBox, SectionTitle } from '../components/ui/Blocks'
import type { Condition, GenerateResponse } from '../types/api'
export default function Explore(){const state=useAppState(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<GenerateResponse|null>(state.baselineResult);async function generate(c:Condition){state.setBaseline(c);setError('');setBusy(true);try{const r=await api.generate({condition:c,n:1000,n_examples:3});state.setBaselineResult(r);state.addHistory(r);setResult(r)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <div className="page"><div className="page-heading"><div><span className="eyebrow">SCENARIO WORKSPACE · 01</span><h1>Explore a reference profile</h1><p>Set the profile conditions, then generate a synthetic cohort summary.</p></div></div><Disclaimer/><SectionTitle eyebrow="PROFILE INPUTS" title="Define your population context">Presets are supported reference combinations from the backend. You can edit each field before generating.</SectionTitle><ProfileForm initial={state.baseline} busy={busy} onSubmit={generate}/>{error&&<ErrorBox message={error} onRetry={()=>state.baseline&&generate(state.baseline)}/ >}{result&&<section className="results-section" id="results"><div className="results-heading"><div><span className="eyebrow">GENERATED RESULT</span><h2>Synthetic Cohort Generated</h2><p>{conditionSummary(result.effective_conditions)}</p></div></div><MetricCard result={result}/><div className="result-detail-grid"><div className="detail-card"><h3>Scenario context</h3><p><b>Effective conditions</b><br/>{conditionSummary(result.effective_conditions)}</p><p><b>Run type</b><br/>{result.run_type?.toUpperCase()??'Unavailable'}{result.demo?' · mock demo':result.preliminary?' · preliminary':''}</p><p><b>Scope</b><br/>{result.scope}</p><p><b>Weighting</b><br/>{result.weighting}</p></div><div className="detail-card"><h3>How to read this result</h3><p>{result.uncertainty_note}</p><p>{result.note}</p><p><b>Elevated in cohort:</b> {Math.round(result.outcome_stat.rate*result.outcome_stat.n).toLocaleString()} of {result.outcome_stat.n.toLocaleString()}</p></div></div><h3 className="subsection-heading">Representative generated examples</h3><p className="muted">These model-generated examples illustrate the cohort and do not determine its summary statistic.</p><Examples result={result}/><div className="result-actions"><Link to="/compare" className="button primary"><GitCompareArrows size={16}/> Explore a what-if comparison <ArrowRight size={16}/></Link><Link to="/scenarios" className="button secondary">View scenario history</Link></div></section>}</div>}
